let afrosoricidas =[
  
  {
    "id": "1",
    "name": "Fynbos golden mole",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "2",
    "name": "Hottentot golden mole",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "3",
    "name": "Marley's golden mole",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "4",
    "name": "Robust golden mole",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "5",
    "name": "Highveld golden mole",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "6",
    "name": "Congo Golden Mole",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "7",
    "name": "Yellow Golden Mole",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "8",
    "name": "Somali Golden Mole",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "9",
    "name": "Arends's golden mole",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "10",
    "name": "Duthie's Golden Mole",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "11",
    "name": "Sclater's Golden Mole",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "12",
    "name": "De Winton's Golden Mole",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "13",
    "name": "Van Zyl's Golden Mole",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "14",
    "name": "Cape Golden Mole",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "15",
    "name": "Visagie's Golden Mole",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "16",
    "name": "Stuhlmann's Golden Mole",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "17",
    "name": "Rough-haired Golden Mole",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "18",
    "name": "Giant Golden Mole",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "19",
    "name": "lesser hedgehog tenrec",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "20",
    "name": "Grant's golden mole",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "21",
    "name": "large-eared tenrec",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "22",
    "name": "web-footed tenrec",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "23",
    "name": "Short-tailed Shrew Tenrec",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "24",
    "name": "Cowan's Shrew Tenrec",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "25",
    "name": "Dobson's Shrew Tenrec",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "26",
    "name": "Drouhard's Shrew Tenrec",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "27",
    "name": "Dryad Shrew Tenrec",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "28",
    "name": "Pale Shrew Tenrec",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "29",
    "name": "Gracile Shrew Tenrec",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "30",
    "name": "Naked-nosed Shrew Tenrec",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "31",
    "name": "Jenkins' Shrew Tenrec",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "32",
    "name": "Northern Shrew Tenrec",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "33",
    "name": "Lesser Long-tailed Shrew Tenrec",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "34",
    "name": "Major's Long-tailed Tenrec",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "35",
    "name": "Montane Shrew Tenrec",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "36",
    "name": "Nasolo's Shrew Tenrec",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "37",
    "name": "Pygmy Shrew Tenrec",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "38",
    "name": "Greater Long-tailed Shrew Tenrec",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "39",
    "name": "Least Shrew Tenrec",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "40",
    "name": "Shrew-toothed Shrew Tenrec",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "41",
    "name": "Taiva Shrew Tenrec",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "42",
    "name": "Talazac's Shrew Tenrec",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "43",
    "name": "Thomas's Shrew Tenrec",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "44",
    "name": "Ruwenzori Otter Shrew",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "45",
    "name": "Nimba Otter Shrew",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "46",
    "name": "Mole-like rice tenrec",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "47",
    "name": "Four-toed rice tenrec",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "48",
    "name": "giant otter shrew",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "49",
    "name": "Greater hedgehog tenrec",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  },
  {
    "id": "50",
    "name": "tailless tenrec",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-12 21:35:38"
  }
]
export default afrosoricidas;