let edentatas = [
  
  {
    "id": "1",
    "name": "Northern Naked-tailed Armadillo",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-13 13:33:25"
  },
  {
    "id": "2",
    "name": "Chacoan Naked-tailed Armadillo",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-13 13:33:25"
  },
  {
    "id": "3",
    "name": "Southern Naked-tailed Armadillo",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-13 13:33:25"
  },
  {
    "id": "4",
    "name": "Greater Naked-tailed Armadillo",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-13 13:33:25"
  },
  {
    "id": "5",
    "name": "greater fairy armadillo",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-13 13:33:25"
  },
  {
    "id": "6",
    "name": "Screaming hairy armadillo",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-13 13:33:25"
  },
  {
    "id": "7",
    "name": "Big hairy armadillo",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-13 13:33:25"
  },
  {
    "id": "8",
    "name": "Andean hairy armadillo",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-13 13:33:25"
  },
  {
    "id": "9",
    "name": "pink fairy armadillo",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-13 13:33:25"
  },
  {
    "id": "10",
    "name": "naked-tailed armadillo",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-13 13:33:25"
  },
  {
    "id": "11",
    "name": "six-banded armadillo",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-13 13:33:25"
  },
  {
    "id": "12",
    "name": "giant armadillo",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-13 13:33:25"
  },
  {
    "id": "13",
    "name": "southern three-banded armadillo",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-13 13:33:25"
  },
  {
    "id": "14",
    "name": "Brazilian three-banded armadillo",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-13 13:33:25"
  },
  {
    "id": "15",
    "name": "pichi",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-13 13:33:25"
  },
  {
    "id": "16",
    "name": "brown-throated sloth",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-13 13:33:25"
  },
  {
    "id": "17",
    "name": "maned sloth",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-13 13:33:25"
  },
  {
    "id": "18",
    "name": "pale-throated sloth",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-13 13:33:25"
  },
  {
    "id": "19",
    "name": "pygmy three-toed sloth",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-13 13:33:25"
  },
  {
    "id": "20",
    "name": "Linnaeus's two-toed sloth",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-13 13:33:25"
  },
  {
    "id": "21",
    "name": "Hoffmann's two-toed sloth",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-13 13:33:25"
  },
  {
    "id": "22",
    "name": "silky anteater",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-13 13:33:25"
  },
  {
    "id": "23",
    "name": "giant anteater",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-13 13:33:25"
  },
  {
    "id": "24",
    "name": "southern tamandua",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-13 13:33:25"
  },
  {
    "id": "25",
    "name": "northern tamandua",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-13 13:33:25"
  }
]

export default edentatas; 