let hyracoideas = [
  
  {
    "id": "1",
    "name": "Eastern tree hyrax",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-13 20:28:24"
  },
  {
    "id": "2",
    "name": "Western tree hyrax",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-13 20:28:24"
  },
  {
    "id": "3",
    "name": "yellow-spotted rock hyrax",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-13 20:28:24"
  },
  {
    "id": "4",
    "name": "rock badger",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "status": "",
    "scientific_name": "",
    "sound": "",
    "kingdom": "",
    "classe": "",
    "order_m": "",
    "suborder_m": "",
    "family": "",
    "location": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-06-13 20:28:24"
  }
]
export default hyracoideas;